---
# role: ansible-role-hosts
# file: tasks/tasks.yml

- name: "Set os_family dependent variables"
  include_vars: '{{ ansible_os_family }}.yml'

- name: "Set distribution dependent variables"
  include_vars: '{{ vars_file }}'
  with_first_found:
    - files:
        - '{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml'
        - '{{ ansible_distribution }}.yml'
        - '{{ ansible_os_family }}-{{ ansible_distribution_major_version }}.yml'
      skip: true
  loop_control:
    loop_var: vars_file

- name: "Install packages for ansible-role-hosts"
  package:
    name: "{{ hosts_packages }}"
    state: present

- name: "Check if dhcp or static configuration"
  command: "ip r"
  changed_when: False
  register: hosts_iproute

- name: "Set fact for testing ip address"
  set_fact:
    hosts_ip_test: |
      {{ hosts_iproute.stdout_lines
      | select('match', '^default .* ' ~ ansible_default_ipv4.interface ~ ' .* dhcp')
      | list
      | length
      }}

- name: "Set fact for dhcp test"
  set_fact:
    hosts_dhcp: "{{ hosts_ip_test | int | bool }}"

- name: "Set fact hosts_fqdn"
  set_fact:
    hosts_fqdn: "{{ ansible_fqdn if ansible_fqdn != ansible_hostname else '' }}"

- name: "Write custom hosts file"
  template:
    src: "etc/hosts.j2"
    dest: "/etc/hosts"
    owner: root
    group: root
    mode: 0644
    backup: "{{ hosts_backup }}"

- name: debug
  debug:
    msg: "{{ ansible_fqdn }} {{ ansible_hostname }} = {{ hosts_fqdn }}"
