---
# role: ansible-role-hosts
# file: molecule/vbox/molecule.yml

dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
    type: virtualbox
lint: |
  set -e
  yamllint .
  ansible-lint
platforms:
  - name: hosts-alpine313
    box: "generic/alpine313"
    cpus: 2
    memory: 1024
  - name: hosts-amazonlinux2
    box: "bento/amazonlinux-2"
    cpus: 2
    memory: 1024
  - name: hosts-arch
    box: "archlinux/archlinux"
    cpus: 2
    memory: 1024
  - name: hosts-centos7
    box: "centos/7"
    cpus: 2
    memory: 1024
  - name: hosts-centos8
    box: "centos/8"
    cpus: 2
    memory: 1024
  - name: hosts-debian9
    box: "debian/stretch64"
    cpus: 2
    memory: 1024
  - name: hosts-debian10
    box: "debian/buster64"
    cpus: 2
    memory: 1024
  - name: hosts-debian11
    box: "debian/bullseye64"
    cpus: 2
    memory: 1024
  - name: hosts-fedora33
    box: "fedora/33-cloud-base"
    cpus: 2
    memory: 1024
  - name: hosts-suse-leap-15
    box: "bento/opensuse-leap-15"
    cpus: 2
    memory: 1024
  - name: hosts-oracle7
    box: "generic/oracle7"
    cpus: 2
    memory: 1024
  - name: hosts-oracle8
    box: "generic/oracle8"
    cpus: 2
    memory: 1024
  - name: hosts-ubuntu1804
    box: "ubuntu/bionic64"
    cpus: 2
    memory: 1024
  - name: hosts-ubuntu2004
    box: "ubuntu/focal64"
    cpus: 2
    memory: 1024
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../resources/playbooks/prepare.yml
    converge: ../resources/playbooks/converge.yml
    verify: ../resources/playbooks/verify.yml
  inventory:
    group_vars:
      all:
        hosts_role_enabled: true
verifier:
  name: ansible
